import type { Metadata } from 'next';
import './globals.css';
import Navigation from '../features/navigation/components/navigation';
import AppProviders from '@/shared/components/providers';
import { AuthContainer } from '@/features/auth/components/auth-container';
import { Toaster } from '@/shared/components/ui/sonner';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className="min-h-screen flex flex-col"
    >
      <body className="bg-background">
        <AppProviders>
          {/* For all pages, navigation is above the content */}
          <Navigation />
          {/* Auth will not show until trigger is clicked in nav */}
          <AuthContainer />
          {children}
          <Toaster />
        </AppProviders>
      </body>
    </html>
  );
}
