import type { Metadata } from 'next';
import './globals.css';
import Navigation from '../features/navigation/components/navigation';
import AppProviders from '@/shared/components/providers';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className="min-h-screen flex flex-col"
    >
      <body className="bg-background">
        <AppProviders>
          {/* for all pages, the navigation is above the content */}
          <Navigation />
          {children}
        </AppProviders>
      </body>
    </html>
  );
}
